# Generated by Django 4.2 on 2023-12-18 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(help_text='Игра', on_delete=django.db.models.deletion.PROTECT, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='energy',
            field=models.ForeignKey(help_text='Энергоресурсы', on_delete=django.db.models.deletion.CASCADE, related_name='energy', to='games.energy', verbose_name='Энергоресурсы'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='natural_resources',
            field=models.ForeignKey(help_text='Природные ресурсы', on_delete=django.db.models.deletion.CASCADE, related_name='natural_resources', to='games.naturalresources', verbose_name='Природные ресурсы'),
        ),
    ]
